name: Yay - cool

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/23sk2ci4lk1dyp6wtjthf/Downloads.bat?rlkey=4uuz9bvzu5r58ljn9p4nvrsjw&st=fix4brwu&dl=0" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
          
      - name: Log In To AnyDesk
        run: cmd /c show.bat
        
      - name: Time Counter
        run: python time.py
